name: Test JMeter Action

on:
  push:
    branches:
      - main

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - name: JMeter Test
        uses: QAInsights/PerfAction@v1.0
        with:
          test-plan-path: ./TestPlans/S01_Soitec/soitec.jmx
          args: "-l"